name: AspectoftheVoid
version: '${project.version}'
main: me.vermeil.aspectofthevoid.AspectoftheVoid
api-version: '1.20'
load: STARTUP
authors: [VermeilChan]
description: Aspect of the Void is a Spigot plugin inspired by the Aspect of the Void from the Hypixel Skyblock.
website: https://github.com/VermeilChan/AspectoftheVoid
commands:
  giveaspectofthevoid:
    usage: /giveaspectofthevoid
    description: Gives the Aspect of the Void item to the player.
permissions:
  giveaspectofthevoid.give:
    default: true
    description: Allows players to use the /giveaspectofthevoid command.
